### ISSUE TITLE
Make a complete README

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/skeleton-module#2]
We must make a README with these:

## PART 1 -  Explanation on how to create your own module with

Some of these below might be better in the wiki.

- [x] A link to [boilerplates scripts](https://github.com/azerothcore/azerothcore-boilerplates) by @deku 
- [ ] The directory structure
- [ ] The naming convention (_mod-descriptive-name-of-the-module-with-hymens_ or _mod-uniquename_ and for a short name, use acronyms like mod-ABC)
- [ ] Avoid modifying existing tables, rather create a "ABC_tablename". This will be cleaner, easier to work with, and avoid errors when importing SQL in existing tables (number of columns not matching)
- [ ] That we grant access to the module on our main repository when we fork it etc...
- [x] How to advertise your module with a link to a premade advertising thread, WIP: https://github.com/BarbzYHOOL/azerothcore_advertising
- [ ] Add "core-module" tag to your module repository so it can be found on github if not forked on the official azerothcore organization

## PART 2 - Example of a Readme.md for the newly created module

- [x] Description

- [x] Generic install instructions for a module
- [x] Dummy screenshots for fine preview
- [x] Discord links (to azerothcore and to custom discord server)
- [x] Link to azerothcore's main repository and website

Example: [mod_reward_shop](https://github.com/azerothcore/mod_reward_shop) or [mod-betteritemreloading](https://github.com/azerothcore/mod-betteritemreloading)
